### ISSUE TITLE
Total Time is always 9223372036854

### ISSUE THREAD

**Issue by WebKenth** [Pixep/crowlet#10]
Not sure if i am doing anything wrong but regardless of any crawl i perform i just get 9223372036854 as a time :-/

using `aleravat/crowlet@sha256:1c23f62c5328f5e79c5b347e0eb4bf10223ebca0bbff80bc38d83206ef79141e`

**Comment by Pixep** [comment]
Hey @WebKenth , thanks for reporting it, and sorry I missed the notification.
That was a while ago, but I will have a look at this.

**Comment by aboritskiy** [comment]
I fixed it here: https://github.com/Pixep/crowlet/pull/11

**Comment by Pixep** [comment]
Confirmed fixed, thanks @aboritskiy for identifying the source of the problem!
