### ISSUE TITLE
memory consumption is not adequate

### ISSUE THREAD

**Issue by aboritskiy** [Pixep/crowlet#12]
crawler seem to be using a lot of memory.

I have a website with ~22K URLs that I need to crawl. I was running crawler on AWS EC2 `t2.micro`, which has ~1 GB of memory.
Crawler was leading this instance to freeze.

I was testing locally with 1GB memory limit, crawler hits it. 

I think 1GB of memory is too much for simple crawler.

I'm not a Go expert and I'm not able to identify memory leak in the code.
I assume that it is about not releasing/cleaning the response results for each crawled URL.

**Comment by Pixep** [comment]
Thank you for your report @aboritskiy . From what I see, it seems that some of our dependences are a bit memory hungry.
Did you try with `--throttle 1`, to limit the number of workers? That should have a positive impact on memory usage.

**Comment by Pixep** [comment]
@aboritskiy I wasn't able to reproduce the exact conditions you described. If you have a sitemap I could for testing or more information, please let me know, and we can re-open this. In the meantime, the latest version might improve a bit the situation for you.
