### ISSUE TITLE
forever not working

### ISSUE THREAD

**Issue by danielslyman** [Pixep/crowlet#14]
hello

docker run -it --rm aleravat/crowlet --forever --wait-interval 5 https://website.com/sitemap.xml

I am running this command, 5 seconds for testing obviously, however the console is not displaying new crawls after the first batch.

Any ideas? Thanks :)

**Comment by Pixep** [comment]
Thank you for the bug report @danielslyman ! Fixed with the above change 🥳

**Comment by danielslyman** [comment]
Much appreciated!
