### ISSUE TITLE
override-host option

### ISSUE THREAD

**Issue by dschmidtadv** [Pixep/crowlet#18]
How can I use this option? It seems to be ignored.

**Comment by Pixep** [comment]
Hi @dschmidtadv , thank you for reporting, and sorry for the delay (notification issue).
This will be added/restored in the next feature drop, and was not properly working as you mentioned.

This will allow overriding the host listed in all the links of the pointed (this one) sitemap, for example to swap dev and production domains. Does that reflect what you needed at the time?
