### ISSUE TITLE
ctrl+c Doesn't exit when waiting for wait-intrval

### ISSUE THREAD

**Issue by VarunBatraIT** [Pixep/crowlet#6]
I used this: 

```

docker run -it --rm aleravat/crowlet --forever --crawl-hyperlinks --summary-only  --debug   --wait-interval 1800 https://webapplicationconsultant.com/sitemap.xml

```

It didn't exit when I pressed Ctrl+c It happens ONLY when it is waiting for 1800 seconds to be over - so when the first crawl is done.

**Comment by Pixep** [comment]
Hi @VarunBatraIT, thanks for reporting it! This should now be fixed on the latest Docker image. Let me know if you have any issue.
